language: node_js
node_js:
- "10.8"
- "8.12"
dist: trusty
env:
dist: trusty
services:
- postgresql
branches:
except:
- gh-pages
- master
before_script:
- psql -c "create database PoliticoTest;" -U postgres
- psql -c "create user emeka with password 'maths102';" -U postgres
- npm install
script:
- npm test
after_success: npm run coverage
