language: node_js
node_js:
  - "stable"
env:
global:
  - export NODE_ENV=test
dist: trusty
addons:
    postgresql: "9.5"
services:
  - postgresql
notifications:
  email: false
cache:
  directories:
    - node_modules
before_script:
  - psql -c "CREATE DATABASE PoliticoTest;" -U postgres
  - psql -c "CREATE USER emeka WITH PASSWORD 'password';" -U postgres
  - npm install
script: 
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls
