language: node_js
node_js:
  - "stable"
env:
global:
  - export NODE_ENV=test
services:
  - postgresql
cache:
  directories:
    - node_modules
before_install:
  - npm install
before_script:
  - psql -c "CREATE DATABASE travis_test_ci;" -U postgres
script: 
  - npm test
after_success:
  - npm run coverage

