language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - node_modules
before_script:
  - npm install
script: 
  - nyc --reporter=lcov --reporter=text-lcov npm test 
after_success: 
  - npm run coverage
 
